"""add cabinet fields

Revision ID: 6d256dd09fbe
Revises: 038a733e599d
Create Date: 2026-04-06 21:52:12.632558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d256dd09fbe'
down_revision = '038a733e599d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_executions')
    op.drop_table('report_favorites')
    op.drop_table('report_templates')
    op.drop_table('scheduled_reports')
    with op.batch_alter_table('cabinets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('depth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('power_supply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('network_access', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cooling_system', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cabinets', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('cooling_system')
        batch_op.drop_column('network_access')
        batch_op.drop_column('power_supply')
        batch_op.drop_column('weight_capacity')
        batch_op.drop_column('depth')
        batch_op.drop_column('width')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('model')

    op.create_table('scheduled_reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('report_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('schedule_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('schedule_config', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('recipients', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('format', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('last_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('next_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('scheduled_reports_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_templates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('report_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('template_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('report_templates_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_favorites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('report_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('parameters', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('report_favorites_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_executions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('report_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('parameters', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('format', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('execution_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('report_executions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
