"""add supplier_id and responsible_user_id to assets

Revision ID: 797ab373ddb0
Revises: 948287cceb15
Create Date: 2026-03-15 19:36:16.122263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797ab373ddb0'
down_revision = '948287cceb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
