"""fix device_config fkey and add monitor tables

Revision ID: d77d2c74533e
Revises: 6d256dd09fbe
Create Date: 2026-04-14 22:56:45.968706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77d2c74533e'
down_revision = '6d256dd09fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('enable_ping', sa.Boolean(), nullable=True),
    sa.Column('ping_interval', sa.Integer(), nullable=True),
    sa.Column('ping_timeout', sa.Float(), nullable=True),
    sa.Column('enable_snmp', sa.Boolean(), nullable=True),
    sa.Column('snmp_version', sa.String(length=8), nullable=True),
    sa.Column('snmp_community', sa.String(length=64), nullable=True),
    sa.Column('snmp_interval', sa.Integer(), nullable=True),
    sa.Column('snmp_timeout', sa.Float(), nullable=True),
    sa.Column('snmp_username', sa.String(length=64), nullable=True),
    sa.Column('snmp_auth_password', sa.String(length=128), nullable=True),
    sa.Column('snmp_priv_password', sa.String(length=128), nullable=True),
    sa.Column('snmp_auth_protocol', sa.String(length=8), nullable=True),
    sa.Column('snmp_priv_protocol', sa.String(length=8), nullable=True),
    sa.Column('enable_ssh', sa.String(length=8), nullable=True),
    sa.Column('ssh_username', sa.String(length=64), nullable=True),
    sa.Column('ssh_password', sa.String(length=256), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_key_file', sa.String(length=256), nullable=True),
    sa.Column('ssh_interval', sa.Integer(), nullable=True),
    sa.Column('ssh_timeout', sa.Float(), nullable=True),
    sa.Column('enable_api', sa.Boolean(), nullable=True),
    sa.Column('api_url', sa.String(length=512), nullable=True),
    sa.Column('api_method', sa.String(length=16), nullable=True),
    sa.Column('api_auth_type', sa.String(length=16), nullable=True),
    sa.Column('api_auth_value', sa.String(length=256), nullable=True),
    sa.Column('api_headers', sa.Text(), nullable=True),
    sa.Column('api_body', sa.Text(), nullable=True),
    sa.Column('api_interval', sa.Integer(), nullable=True),
    sa.Column('api_timeout', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('retry_interval', sa.Integer(), nullable=True),
    sa.Column('monitor_metrics', sa.Text(), nullable=True),
    sa.Column('inherit_alerts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('alert_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_config_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.String(length=8), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('notify_channels', sa.JSON(), nullable=True),
    sa.Column('notify_targets', sa.JSON(), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['device_config_id'], ['device_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_config_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_config_id'], ['device_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('device_config_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(length=8), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['device_config_id'], ['device_config.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_history')
    op.drop_table('metric_data')
    op.drop_table('alert_rule')
    op.drop_table('device_config')
    # ### end Alembic commands ###
